// backend/index.js
import express from 'express';
import cors from 'cors';
import multer from 'multer';
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname  = path.dirname(__filename);
const app        = express();
const PORT       = process.env.PORT || 5050;

// Middleware
app.use(cors());
app.use(express.json());

// Serve uploads as static so GET /uploads/… works
const UPLOAD_DIR = path.join(__dirname, 'uploads');
if (!fs.existsSync(UPLOAD_DIR)) fs.mkdirSync(UPLOAD_DIR);
app.use('/uploads', express.static(UPLOAD_DIR));

// Multer storage configuration
const storage = multer.diskStorage({
  destination: UPLOAD_DIR,
  filename: (req, file, cb) => {
    const timestamp = Date.now();

    // Assume file.originalname is already in a usable encoding (likely UTF-8).
    let originalname = file.originalname;

    // Normalize and sanitize the filename
    const safe = originalname
      .normalize('NFC') // Use NFC normalization for combining characters
      .replace(/\s+/g, '_') // Replace spaces with underscores
      // Allow Greek characters, standard ASCII letters, numbers, underscore, hyphen, and dot
      .replace(/[^Α-Ωα-ωΆ-Ώά-ώA-Za-z0-9_.-]/g, '');

    // Construct the final filename that will be saved in the uploads folder
    const finalFilename = `${timestamp}-${safe}`;

    // Pass the final filename to Multer
    cb(null, finalFilename);
  }
});
const upload = multer({ storage });

// Healthcheck endpoint
app.get('/', (_req, res) => {
  res.send('CV Platform Backend API is running');
});

// Upload endpoint for CV files
app.post('/api/upload', upload.single('cv'), (req, res) => {
  // **DEBUGGING LOGS:** Print req.file and req.file.filename before processing
  console.log('req.file:', req.file);
  console.log('req.file.filename BEFORE path.basename:', req.file.filename); // Check this output

  // Check if a file was actually uploaded
  if (!req.file) {
    return res.status(400).json({ message: 'No file uploaded' });
  }

  // Extract user data from the request body
  const { name, email, experience } = req.body;
  let { categories }                = req.body;

  // **FIX:** Parse the JSON string for categories received from the frontend
  try {
    categories = JSON.parse(categories);
    // Ensure categories is an array even after parsing
    if (!Array.isArray(categories)) {
        categories = [];
    }
  } catch (e) {
      console.error("Failed to parse categories JSON string:", e);
      categories = []; // Default to empty array on error
  }

  // Multer saved the file, req.file.filename is the name generated by storage.filename
  const savedFilename = req.file.filename;

  // Create user data object to be stored
  const userData = {
    name,
    email,
    experience,
    // Store categories as a correctly parsed array
    categories: categories,
    // **FIX:** Store the filePath INCLUDING the 'uploads/' prefix
    // This matches what the frontend expects for constructing the view URL
    filePath: `uploads/${savedFilename}` // Include the directory prefix
  };

  // Define directory for storing user data JSON files
  const DATA_DIR = path.join(__dirname, 'data');
  // Create data directory if it doesn't exist
  if (!fs.existsSync(DATA_DIR)) {
    fs.mkdirSync(DATA_DIR);
  }

  // Define the path for the output JSON file
  // Use the saved filename (without the uploads/ prefix) for the JSON file name itself
  const jsonFilename = `${Date.now()}-${savedFilename}.json`;
  const outFile = path.join(DATA_DIR, jsonFilename);

  try {
    // Write user data to the JSON file with UTF-8 encoding
    fs.writeFileSync(outFile, JSON.stringify(userData, null, 2), 'utf8');
    // Send success response, returning the stored filePath (including uploads/)
    res.json({ message: 'CV uploaded successfully', file: userData.filePath });
  } catch (error) {
    // Handle potential file writing errors
    console.error("Error writing user data file:", error);
    res.status(500).json({ message: 'Error saving user data' });
  }
});

// List CVs endpoint with optional category filter
app.get('/api/cvs', (req, res) => {
  const { category } = req.query; // Get category filter from query parameters
  const DATA_DIR = path.join(__dirname, 'data');

  // If data directory doesn't exist, return empty array
  if (!fs.existsSync(DATA_DIR)) {
    return res.json([]);
  }

  try {
    // Read all JSON files from the data directory
    const cvs = fs
      .readdirSync(DATA_DIR)
      .filter(f => f.endsWith('.json')) // Only process JSON files
      .map(f => {
        try {
          // Parse each JSON file
          const data = fs.readFileSync(path.join(DATA_DIR, f), 'utf8');
          return JSON.parse(data);
        } catch (parseError) {
          console.error(`Error parsing JSON file ${f}:`, parseError);
          return null; // Return null for files that fail to parse
        }
      })
      .filter(cv => cv !== null); // Filter out any null entries from parsing errors

    // **FIX:** Filter CVs based on if the categories array includes the selected category
    // Ensure categories is an array before trying to include
    const filtered = category
      ? cvs.filter(cv => Array.isArray(cv.categories) && cv.categories.includes(category))
      : cvs; // If no category, return all CVs

    // Send the filtered (or all) CV data
    res.json(filtered);
  } catch (error) {
    // Handle errors during file reading or processing
    console.error("Error retrieving CV data:", error);
    res.status(500).json({ message: 'Error retrieving CV data' });
  }
});

// Start the server
app.listen(PORT, () => {
  console.log(`Server running on http://localhost:${PORT}`);
});